import os
import glob
from datetime import datetime

VAULT_DIR = "/home/khyha/projects/Sunny"

def read_moc(folder_keyword):
    """
    Search for a Map of Content (MOC) matching the keyword and return its links.
    Agent should use this to find out what files exist in a domain before reading them.
    """
    search_pattern = f"{VAULT_DIR}/**/*{folder_keyword}*_MOC.md"
    moc_files = glob.glob(search_pattern, recursive=True)
    
    if not moc_files:
        return f"No MOC found for keyword: {folder_keyword}"
        
    result = []
    for moc_path in moc_files:
        with open(moc_path, 'r', encoding='utf-8') as f:
            content = f.read()
        result.append(f"--- MOC: {os.path.basename(moc_path)} ---\n{content}\n")
        
    return "\n".join(result)

def write_lesson_learned(folder_path_relative, title, content, tags=None,
                          note_type="lesson", summary="", auto_enrich=False):
    """
    Active Learning function. The Agent calls this to save new findings.
    It creates a perfectly formatted Markdown file and updates the corresponding MOC.
    
    Args:
        note_type: "lesson" | "reference" | "concept" | "project" | "daily-log"
        summary: 1~2줄 요약 (비어있고 auto_enrich=True면 AI가 생성)
        auto_enrich: True면 저장 후 ontology_enricher로 AI 보강 (WikiLink+Entity)
    """
    if tags is None:
        tags = []
        
    target_dir = os.path.join(VAULT_DIR, folder_path_relative)
    if not os.path.exists(target_dir):
        os.makedirs(target_dir, exist_ok=True)
        
    # Prepare Frontmatter
    domain = folder_path_relative.split(os.sep)[0].lower().replace(" ", "-") if folder_path_relative else "root"
    all_tags = list(dict.fromkeys([domain] + tags))  # 중복 제거
    tags_str = "\n  - ".join(all_tags)
    
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{date_str}_{title.replace(' ', '_')}.md"
    filepath = os.path.join(target_dir, filename)
    
    summary_val = summary if summary else "Auto-generated by Agent"
    
    md_content = f"""---
type: {note_type}
tags:
  - {tags_str}
created: {date_str}
summary: "{summary_val}"
---
# {title}

{content}
"""
    # Write the new file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(md_content)
        
    # Update the MOC
    folder_name = os.path.basename(target_dir) or domain
    moc_filename = f"00_{folder_name}_MOC.md"
    moc_path = os.path.join(target_dir, moc_filename)
    
    if os.path.exists(moc_path):
        with open(moc_path, 'a', encoding='utf-8') as f:
            f.write(f"- [[{filename.replace('.md', '')}]]\n")
    
    # Auto-enrich with AI if requested
    if auto_enrich:
        try:
            import sys as _sys
            _sys.path.insert(0, os.path.join(VAULT_DIR, "scripts"))
            from ontology_enricher import enrich_note
            enrich_note(filepath)
        except Exception as e:
            print(f"  ⚠️ Auto-enrich 실패 (노트는 저장됨): {e}")
            
    return f"Success: Saved {filename} to {folder_path_relative} and updated MOC."

# Example Agent Tool Wrappers (for LangChain, CrewAI, or direct OpenClaw usage)
if __name__ == "__main__":
    # Test reading
    print(read_moc("OpenClaw"))
